Task1_0723. 'Breast Cancer Wisconsin (Diagnostic) Data Set'을 사용하여 이진 분류 문제를 해결하고, 평가 지표(정확도, 정밀도, 재현율, F1 스코어, ROC AUC)를 계산하세요.

In [ ]:
# 데이터 로드
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_score, recall_score, f1_score, roc_auc_score
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=0.2, random_state = 42)

model = LogisticRegression()
model.fit(X_train,y_train)

pred = model.predict(X_test)
pred_proba = model.predict_proba(X_test)[:,1].reshape(-1,1)

def result(y_test, pred,pred_proba):
    confusion = confusion_matrix(y_test, pred)
    accuracy = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred)
    recall = recall_score(y_test, pred)
    f1= f1_score(y_test, pred)
    roc_auc = roc_auc_score(y_test,pred_proba)
    print("오차행렬")
    print(confusion)
    print('정확도 : {0:.4f}, 정밀도 : {1:.4f}, 재현율 : {2:.4f}, F1 : {3:.4f}, AUC: {4:.4f}'.format(accuracy,precision,recall,f1,roc_auc))

result(y_test,pred,pred_proba)

오차행렬
[[40  3]
 [ 1 70]]
정확도 : 0.9649, 정밀도 : 0.9589, 재현율 : 0.9859, F1 : 0.9722, AUC: 0.9971


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_score, recall_score, f1_score, roc_auc_score

from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()

X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state = 42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

def train_and_evaluate(model, X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:,1]

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall= recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    roc_auc = roc_auc_score(y_test, y_proba)
    confusion = confusion_matrix(y_test, y_pred)


    print(f"오차 행렬: \n{confusion}")
    print(f"정확도 : {accuracy : .4f}")
    print(f"정밀도 : {precision: .4f}")
    print(f"재현율 : {recall : .4f}")
    print(f"F1 스코어 : {f1: .4f}")
    print(f"ROC AUC : {roc_auc : .4f}")
    print('')


# 여러 모델 훈련 및 평가
models = {
    'Logistic Regression' : LogisticRegression(max_iter=500, solver='lbfgs', random_state =42),
    'Random Forest' : RandomForestClassifier(random_state=42),
    'Support Vector Machine' : SVC(probability=True, random_state=42) # probability=True는 확률 값을 반환하게 하여 predict_proba 메서드를 사용할 수 있게 함
}

for model_name, model in models.items():
    print(f'[{model_name}]')
    train_and_evaluate(model, X_train, X_test, y_train, y_test)

[Logistic Regression]
오차 행렬: 
[[41  2]
 [ 1 70]]
정확도 :  0.9737
정밀도 :  0.9722
재현율 :  0.9859
F1 스코어 :  0.9790
ROC AUC :  0.9974

[Random Forest]
오차 행렬: 
[[40  3]
 [ 1 70]]
정확도 :  0.9649
정밀도 :  0.9589
재현율 :  0.9859
F1 스코어 :  0.9722
ROC AUC :  0.9953

[Support Vector Machine]
오차 행렬: 
[[41  2]
 [ 0 71]]
정확도 :  0.9825
정밀도 :  0.9726
재현율 :  1.0000
F1 스코어 :  0.9861
ROC AUC :  0.9974



Task2_0723.
가상의 데이터셋을 생성하고, 이를 사용하여 다중 클래스 분류 모델을 훈련시킨 후 평가 지표를 계산하세요. 평가 지표는 정확도, 정밀도, 재현율, F1 스코어, ROC AUC입니다.

In [ ]:
# 데이터 생성 (5개의 클래스)
X, y = make_classification(n_samples=1500, n_features=20, n_classes=5, n_informative=15, random_state=42)


# 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X ,y , test_size=0.2, random_state=42)

# 모델 훈련
model = RandomForestClassifier()
model.fit(X_train, y_train)

# 예측 확률
pred = model.predict(X_test)
pred_proba = model.predict_proba(X_test)

# 다중 클래스 라벨을 이진화
y_test_binarized = label_binarize(y_test, classes=[0,1,2,3,4])

roc_auc = roc_auc_score(y_test_binarized,pred_proba,average='macro')


def result(y_test, pred,pred_proba):
    confusion = confusion_matrix(y_test, pred)
    accuracy = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred,average='macro')
    recall = recall_score(y_test, pred,average='macro')
    f1= f1_score(y_test, pred,average='macro')
    print('정확도 : {0:.4f}, 정밀도 : {1:.4f}, 재현율 : {2:.4f}, F1 : {3:.4f}, AUC: {4:.4f}'.format(accuracy,precision,recall,f1,roc_auc))

result(y_test,pred,pred_proba)

정확도 : 0.7800, 정밀도 : 0.7827, 재현율 : 0.7833, F1 : 0.7810, AUC: 0.9449


In [ ]:
import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix
from sklearn.preprocessing import label_binarize

# 데이터 생성 (5개의 클래스)
X, y = make_classification(n_samples=1500, n_features=20, n_classes=5, n_informative=15, random_state=42)

# 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 모델 훈련
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# 예측
y_pred = model.predict(X_test)
y_score = model.predict_proba(X_test)

# 다중 클래스 라벨을 이진화
y_test_binarized = label_binarize(y_test, classes=[0, 1, 2, 3, 4])

# 평가 지표 계산
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='macro')
recall = recall_score(y_test, y_pred, average='macro')
f1 = f1_score(y_test, y_pred, average='macro')
roc_auc = roc_auc_score(y_test_binarized, y_score, multi_class='ovr')
confusion = confusion_matrix(y_test, y_pred)

print(f'오차 행렬:\n{confusion}')
print(f'정확도: {accuracy:.4f}')
print(f'정밀도: {precision:.4f}')
print(f'재현율: {recall:.4f}')
print(f'F1 스코어: {f1:.4f}')
print(f'ROC AUC: {roc_auc:.4f}')


오차 행렬:
[[52  6  2  7  1]
 [ 1 46  2  0  5]
 [ 0  6 49  2  2]
 [ 5  2  4 46  6]
 [ 5  4  2  1 44]]
정확도: 0.7900
정밀도: 0.7909
재현율: 0.7926
F1 스코어: 0.7898
ROC AUC: 0.9481


Task3_0723. 주어진 코드를 수정해서 모델의 성능을 개선하세요

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


#  데이터 로드
import pandas as pd
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data'
columns = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status',
           'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss',
           'hours-per-week', 'native-country', 'income']
data = pd.read_csv(url, header=None, names=columns, na_values='?', skipinitialspace=True)

df = data.copy()

# 상관계수 파악을 위해 0과 1로 변환
df['income'] = df['income'].map({'<=50K':0,'>50K':1})
df['sex'] = df['sex'].map({'Male':0,'Female':1})

# 상관계수 파악 후 자본 이득, 손실의 계수가 높아서 파생변수 생성
df['capital-diff'] = df['capital-gain'] - df['capital-loss']


# 불필요한 열 : education, fnlwgt, capital-gain, capital-loss, hours-per-week 삭제
df.drop(['education', 'fnlwgt', 'capital-gain', 'capital-loss', 'hours-per-week'],axis=1,inplace=True)


# 결측치 제거
df['workclass'].fillna(df['workclass'].mode()[0], inplace = True)
df['occupation'].fillna(df['occupation'].mode()[0], inplace=True)
df['native-country'].fillna(df['native-country'].mode()[0], inplace=True)
print(df.isnull().sum())


# 범주형 변수 인코딩
for column in df.columns:
    # 첫 번재 카테고리는 drop_first=True로 열 제거
    df = pd.get_dummies(df, columns=[column], drop_first = True)

# 타겟 변수와 피처 변수 설정
X = df.drop('income_1', axis=1)
y = df['income_1']

# 학습 데이터와 테스트 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = LogisticRegression()
model.fit(X_train, y_train)

# 예측
y_pred = model.predict(X_test)


# 성능 평가
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

age               0
workclass         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
native-country    0
income            0
capital-diff      0
dtype: int64
Accuracy: 0.8754798096115461
Confusion Matrix:
 [[4663  279]
 [ 532 1039]]
Classification Report:
               precision    recall  f1-score   support

       False       0.90      0.94      0.92      4942
        True       0.79      0.66      0.72      1571

    accuracy                           0.88      6513
   macro avg       0.84      0.80      0.82      6513
weighted avg       0.87      0.88      0.87      6513



/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
