## Numpy Quiz1

Q1. arange(), reshape() 이용 1차원 2차원 3차원 배열 생성

In [2]:
import numpy as np

a1 = np.arange(18)
a2 = a1.reshape(3,6)
a3 = a1.reshape(3,2,3)
print(f"1차원 {a1}",'\n')
print(f"2차원 {a2}",'\n')
print(f"3차원 {a3}")

1차원 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17] 

2차원 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]] 

3차원 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


Q2. reshape(-1,-1)을 이용 1차원을 2차원, 3차원으로 2차원을 1차원 3차원으로 3차원을 1차원 2차원으로 변환

In [4]:
ar1 = np.arange(24)
ar2 = ar1.reshape(3,-1)
ar3 = ar1.reshape(3,2,-1)
print(f"1차원 {ar1}",'\n')
print(f"2차원 변환 \n {ar2}",'\n')
print(f"3차원 변환 \n {ar3}")

1차원 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] 

2차원 변환 
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]] 

3차원 변환 
 [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


Q3. Q1 1차원 배열을 실수형으로 변환

In [8]:
ar1 = np.arange(10)
print(ar1,ar1.dtype)
ar1_f = ar1.astype(float)
print(ar1_f,ar1_f.dtype)

[0 1 2 3 4 5 6 7 8 9] int64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64


Q4. Q1 1차원 배열의 dtype을 확인

In [9]:
ar1 = np.arange(5)
print(ar1.dtype)

int64


Q5. 주어진 배열에서 음수 값을 모두 0으로 변경하세요.

arr = np.array([-5, -3, -1, 0, 1, 3, 5])

In [14]:
arr= np.array([-5,-3,-1,0,1,3,5])
print(arr,'\n')
arr[arr<0] = 0
print(arr)

[-5 -3 -1  0  1  3  5] 

[0 0 0 0 1 3 5]


Q6. 1 ~ 100 까지 배열에서 3의 배수인 것만을 출력

In [15]:
ar = np.arange(1,101)

ar[ar % 3 == 0]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

Q7. 1 ~ 100 까지 배열에서 5의 배수이면서 2의 배수인 것만을 출력

In [16]:
ar = np.arange(1,101)

ar[(ar % 5 == 0) & (ar % 2 == 0)]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

Q8. 1 ~ 100 까지 배열에서 3의 배수이거나 5의 배수인 것만을 출력

In [17]:
ar = np.arange(1,101)

ar[(ar % 3 == 0) | (ar % 5 == 0)]

array([  3,   5,   6,   9,  10,  12,  15,  18,  20,  21,  24,  25,  27,
        30,  33,  35,  36,  39,  40,  42,  45,  48,  50,  51,  54,  55,
        57,  60,  63,  65,  66,  69,  70,  72,  75,  78,  80,  81,  84,
        85,  87,  90,  93,  95,  96,  99, 100])

Q9. 101 ~ 150 사이의 정수를 랜덤하게 추출, 2행 5열 다차원 배열을 생성 후 전치하세요

In [21]:
ar = np.random.randint(101,151,size = 10)
ar_1 = ar.reshape(2,5)
print(ar_1.T)

[[108 120]
 [114 142]
 [133 118]
 [135 122]
 [149 115]]


Q10. 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하세요.

In [22]:
ar = np.random.randn(25).reshape(5,5)
print(ar)

[[-0.15820934  0.10460666 -1.38033735  0.55449432 -2.75276356]
 [-0.47941877 -0.91231554 -0.59731729  0.30547643 -0.21207012]
 [ 0.74919981 -0.87795975  1.00435829  0.81035175  1.20800064]
 [-0.68237327 -0.5104942   0.43784893  1.00185135 -0.5267872 ]
 [ 0.1031725  -0.65422933 -0.3077938   1.0783671   1.17886735]]


Q11. original_array를 1차원 배열로 변환하여 출력하세요.

In [25]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])
trans_original_array = original_array.reshape(-1)
# 배열.flatten() -> 1차원 변환
print(trans_original_array)

[1 2 3 4 5 6]


Q12. 주어진 2차원 배열에서 첫 번째 행을 view로 생성하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[1, 2, 3], [4, 5, 6]])

In [32]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])

original_array_view = original_array[0]
print('기존의 view',original_array_view,'\n')
original_array_view[2] = 4

print("수정된 view", original_array_view,'\n')
print('기존 array', original_array)

기존의 view [1 2 3] 

수정된 view [1 2 4] 

기존 array [[1 2 4]
 [4 5 6]]


Q13. 주어진 3차원 배열에서 첫 번째 2차원 배열을 view로 생성하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [33]:
original_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

original_array_v = original_array[0]
print('기존의 view',original_array_v,'\n')
original_array_v[0][2] = 4
print("수정된 view", original_array_v,'\n')
print('기존 array', original_array)

기존의 view [[1 2 3]
 [4 5 6]] 

수정된 view [[1 2 4]
 [4 5 6]] 

기존 array [[[ 1  2  4]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Q14. 주어진 2차원 배열을 1차원 배열 view로 reshape하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[1, 2, 3], [4, 5, 6]])

In [35]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])

original_array_1 = original_array.reshape(-1)
print('기존 view', original_array_1,'\n')
original_array_1[0] = 0
print("변경된 view",original_array_1,'\n')
print('기존 array', original_array)

기존 view [1 2 3 4 5 6] 

변경된 view [0 2 3 4 5 6] 

기존 array [[0 2 3]
 [4 5 6]]


Q15. np.ones((10,10))을 아래와 같이 출력하세요.
```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
 ```

In [42]:
ones = np.ones((10,10))
ones[1:-1,1:-1] = 0

print(ones)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Q16. Q. 1 ~ 100을 아래와 같이 출력하세요.

```
[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]
 ```

In [47]:
ar = np.arange(1,101).reshape(10,-1)
# 행이 짝수일 때마다 내림차순 정렬
for i in range(10):
    if (i != 0) and (i % 2 != 0):
        ar[i] = ar[i][::-1]
print(ar)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]


Q17. np.ones((5,5))을 아래와 같이 출력하세요.
```
[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]]
```

In [49]:
ar = np.ones((5,5))
print(ar)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Q18. np.arange(4)을 이용해서 아래와 같이 출력하세요.
```
[[0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 2, 0, 0, 0],
 [0, 0, 3, 0, 0],
 [0, 0, 0, 4, 0]]
```

In [50]:
ar = np.arange(4)
print(ar)

[0 1 2 3]


Q19. Q. np.zeros((8,8))을 이용해서 아래와 같이 출력하세요(두가지 방식:인덱싱, tile 함수)
```
[[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0]]
```

In [58]:
ar = np.zeros((8,8))
for i in range(8):
    if i % 2 == 1:
        ar[i][[0,2,4,6]] = 1
    else:
        ar[i][[1,3,5,7]] = 1
print(ar)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Q20. np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요.

In [67]:
ar = np.arange(336).reshape(6,7,8)
ar_1 = ar.reshape(-1)
element = ar_1[99]
np.where(ar == element)

(array([1]), array([5]), array([3]))