## Contetnts
- 기초 연산
- 그룹 연산 : 집계, 변환, 필터링, 그룹매핑
- 함수 매핑 : map, apply, applymap
- Pivot

#### 기초연산

In [ ]:
import pandas as pd

st1 = pd.Series({'국어':100,'영어':80,'수학':90})
st2 = pd.Series({'수학':80,'국어':90,'영어':80})

print(st1,'\n')
print(st2)

국어    100
영어     80
수학     90
dtype: int64 

수학    80
국어    90
영어    80
dtype: int64


In [ ]:
pd.DataFrame(st1+st2)

0
국어  190
수학  170
영어  160

In [ ]:
# 두 학생의 과목별 점수로 사칙연산 수행
add = st1+st2
sub = st1-st2
mul = st1*st2
div = round((st1/st2),2)
df = pd.concat([add,sub,mul,div],axis = 1)
print(df)

      0   1     2     3
국어  190  10  9000  1.11
수학  170  10  7200  1.12
영어  160   0  6400  1.00


In [ ]:
df = pd.concat([add,sub,mul,div],axis = 1)
df.columns = ['덧셈','뺄셈','곱셈','나눗셈']
df

덧셈  뺄셈    곱셈   나눗셈
국어  190  10  9000  1.11
수학  170  10  7200  1.12
영어  160   0  6400  1.00

In [ ]:
print(add,type(add))

국어      NaN
수학    170.0
영어      NaN
dtype: float64 <class 'pandas.core.series.Series'>


In [ ]:
result = pd.DataFrame([add,sub,mul,div])
result

국어       수학      영어
0   190.00   170.00   160.0
1    10.00    10.00     0.0
2  9000.00  7200.00  6400.0
3     1.11     1.12     1.0

In [ ]:
# series끼리 연결이므로
result1 = pd.concat([add,sub,mul,div])
result1

국어     190.00
수학     170.00
영어     160.00
국어      10.00
수학      10.00
영어       0.00
국어    9000.00
수학    7200.00
영어    6400.00
국어       1.11
수학       1.12
영어       1.00
dtype: float64

In [ ]:
result = pd.DataFrame([add,sub,mul,div],index = ['덧셈','뺄셈','곱셈','나눗셈'] )
result

국어       수학      영어
덧셈    190.00   170.00   160.0
뺄셈     10.00    10.00     0.0
곱셈   9000.00  7200.00  6400.0
나눗셈     1.11     1.12     1.0

In [ ]:
import pandas as pd

# 예제 데이터프레임 생성
df11 = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df22 = pd.DataFrame({'A': [7, 8, 9], 'B': [10, 11, 12]})

# 컬럼 이름을 유지하며 데이터프레임 연결
result = pd.concat([df11, df22], keys=['df11', 'df22'])
result1 = pd.concat([add,sub,mul,div])

print(result)
print()
print(result1)

        A   B
df11 0  1   4
     1  2   5
     2  3   6
df22 0  7  10
     1  8  11
     2  9  12

국어        NaN
수학     170.00
영어        NaN
국어        NaN
수학      10.00
영어        NaN
국어        NaN
수학    7200.00
영어        NaN
국어        NaN
수학       1.12
영어        NaN
dtype: float64


In [ ]:
import numpy as np

st1 = pd.Series({'국어':np.nan,'영어':80,'수학':90})
st2 = pd.Series({'수학':80,'국어':90})

add = st1 + st2
sub = st1 - st2
mul = st1 * st2
div = round((st1 / st2),2)

result = pd.DataFrame([add,sub,mul,div],
                     index=['덧셈','뺄셈','곱셈','나눗셈'])
result

국어       수학  영어
덧셈  NaN   170.00 NaN
뺄셈  NaN    10.00 NaN
곱셈  NaN  7200.00 NaN
나눗셈 NaN     1.12 NaN

In [ ]:
# Q. nul값을 0으로 변경
# 연산 했을 때 null인 값들을 0으로 변경
result.fillna(0,inplace=True)
result

국어       수학   영어
덧셈   0.0   170.00  0.0
뺄셈   0.0    10.00  0.0
곱셈   0.0  7200.00  0.0
나눗셈  0.0     1.12  0.0

In [ ]:
# Q. nul값을 0으로 변경
# null값 자체를 0으로 만들어서 연산
st1 = pd.Series({'국어':np.nan,'영어':80,'수학':90})
st2 = pd.Series({'수학':80,'국어':90})

ad = st1.add(st2,fill_value = 0)
su = st1.sub(st2,fill_value = 0)
mu = st1.mul(st2,fill_value = 0)
di = st1.div(st2,fill_value = 0)

df = pd.DataFrame([ad,su,mu,di],
                  index = ['덧셈','뺄셈','곱셈','나눗셈'])

print(df)

       국어        수학    영어
덧셈   90.0   170.000  80.0
뺄셈  -90.0    10.000  80.0
곱셈    0.0  7200.000   0.0
나눗셈   0.0     1.125   inf


In [ ]:
# reshape :  0행 0열로 만들어줌
# arange(12.) : 실수로 만든다 ex) 0. , 1. '''

df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns = list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns = list('abcde'))

print(df1,'\n')
print(df2)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0 

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [ ]:
df2.loc[1,'b'] = np.nan
print(df1)
print(df2)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [ ]:
df1+df2
# df1에 3, e가 없으므로 모두 nan 출력

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [4]:
# Task1_0528. 연산메소드 이용 및 NaN 값을 0으로 대체 후 사칙연산을 수행한 후 결과를 출력하세요.
import numpy as np
import pandas as pd
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns = list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns = list('abcde'))

In [8]:
add = df2.add(df1, fill_value = 0).fillna(0)
sub = df2.sub(df1, fill_value = 0).fillna(0)
mul = df2.mul(df1, fill_value = 0).fillna(0)
div = df2.div(df1, fill_value = 0).fillna(0)

print("데이터 프레임 덧셈:\n",add)
print("데이터 프레임 뺄셈:\n",sub)
print("데이터 프레임 곱셈:\n",mul)
print("데이터 프레임 나눗셈:\n",div)

데이터 프레임 덧셈:
       a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0
데이터 프레임 뺄셈:
       a     b     c     d     e
0   0.0   0.0   0.0   0.0   4.0
1   1.0   1.0   1.0   1.0   9.0
2   2.0   2.0   2.0   2.0  14.0
3  15.0  16.0  17.0  18.0  19.0
데이터 프레임 곱셈:
       a     b      c      d    e
0   0.0   1.0    4.0    9.0  0.0
1  20.0  30.0   42.0   56.0  0.0
2  80.0  99.0  120.0  143.0  0.0
3   0.0   0.0    0.0    0.0  0.0
데이터 프레임 나눗셈:
       a         b         c         d    e
0  0.00  1.000000  1.000000  1.000000  inf
1  1.25  1.200000  1.166667  1.142857  inf
2  1.25  1.222222  1.200000  1.181818  inf
3   inf       inf       inf       inf  inf


In [5]:
add_data = df1.add(df2, fill_value = 0)
sub_data = df1.sub(df2, fill_value = 0)
mul_data = df1.mul(df2, fill_value = 0)
div_data = df1.div(df2, fill_value = 0)
print("데이터 프레임 덧셈:\n",add_data)
print("데이터 프레임 뺄셈:\n",sub_data)
print("데이터 프레임 곱셈:\n",mul_data)
print("데이터 프레임 나눗셈:\n",div_data)

데이터 프레임 덧셈:
       a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0
데이터 프레임 뺄셈:
       a     b     c     d     e
0   0.0   0.0   0.0   0.0  -4.0
1  -1.0  -1.0  -1.0  -1.0  -9.0
2  -2.0  -2.0  -2.0  -2.0 -14.0
3 -15.0 -16.0 -17.0 -18.0 -19.0
데이터 프레임 곱셈:
       a     b      c      d    e
0   0.0   1.0    4.0    9.0  0.0
1  20.0  30.0   42.0   56.0  0.0
2  80.0  99.0  120.0  143.0  0.0
3   0.0   0.0    0.0    0.0  0.0
데이터 프레임 나눗셈:
      a         b         c         d    e
0  NaN  1.000000  1.000000  1.000000  0.0
1  0.8  0.833333  0.857143  0.875000  0.0
2  0.8  0.818182  0.833333  0.846154  0.0
3  0.0  0.000000  0.000000  0.000000  0.0


In [ ]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [ ]:
# 계산인자를 뒤집어 계산
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [ ]:
print(df1)
# 1에서 df1의 값을 뺀다
# ex) 1 - (0,b)-> 즉 1.0이므로 1-1 = 0
df1.rsub(1)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


a    b    c     d
0  1.0  0.0 -1.0  -2.0
1 -3.0 -4.0 -5.0  -6.0
2 -7.0 -8.0 -9.0 -10.0

In [ ]:
print(df1)
df1.radd(1)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


a     b     c     d
0  1.0   2.0   3.0   4.0
1  5.0   6.0   7.0   8.0
2  9.0  10.0  11.0  12.0

In [ ]:
print(df1)
df1.rmul(10)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


a     b      c      d
0   0.0  10.0   20.0   30.0
1  40.0  50.0   60.0   70.0
2  80.0  90.0  100.0  110.0

In [ ]:
arr = np.arange(12.).reshape(3,4)
print(arr,'\n')
print(arr[0])

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] 

[0. 1. 2. 3.]


In [ ]:
# broadcasting
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [ ]:
# DataFrame과 Series간 연산
frame = pd.DataFrame(np.arange(12.).reshape(4,3),columns=list('bde'),
                    index = ['Utah','Ohio','Texas','Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [ ]:
dk = frame.iloc[:,0]
print(dk, type(dk))

Utah      0.0
Ohio      3.0
Texas     6.0
Oregon    9.0
Name: b, dtype: float64 <class 'pandas.core.series.Series'>


In [ ]:
frame-dk

Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

In [ ]:
series = frame.iloc[0]
print(series,type(series))

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64 <class 'pandas.core.series.Series'>


In [ ]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [ ]:
a = np.arange(6).reshape(1,6)
a

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
# 튜플형태로 사용하기위해 콤마 사용
a = np.arange(6).reshape(6,)
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
# Task2_0528. 주어진 DataFrame의 N열에서 Series s값을 빼고 결과를 새로운 열 O에 저장 후 출력하세요.
import pandas as pd

# 데이터프레임 생성
df = pd.DataFrame({
    "M": [15, 25, 35, 45, 55],
    "N": [100, 200, 300, 400, 500]
})
print(df,'\n')
# Series 생성
s = pd.Series([5, 10, 15, 20, 25])
s

    M    N
0  15  100
1  25  200
2  35  300
3  45  400
4  55  500 



0     5
1    10
2    15
3    20
4    25
dtype: int64

In [ ]:
d = df.loc[:,'N']
df['o'] = d - s
# df['o'] = df['N'] - s

df

M    N    o
0  15  100   95
1  25  200  190
2  35  300  285
3  45  400  380
4  55  500  475

In [10]:
# Task3_0528. 주어진 DataFrame의 여러 열에 대해 각기 다른 Series를 더하고, 결과를 새로운 DataFrame으로 반환한 후 각 행의 합계를 계산하여 새로운 열에 추가하여 출력하세요.

import pandas as pd

# 데이터프레임 생성
df = pd.DataFrame({
    "A": [1, 2, 3, 4, 5],
    "B": [10, 20, 30, 40, 50],
    "C": [100, 200, 300, 400, 500]
})

# Series 생성
s1 = pd.Series([5, 5, 5, 5, 5])
s2 = pd.Series([10, 10, 10, 10, 10])
s3 = pd.Series([15, 15, 15, 15, 15])

t1 = df['A'] + s1
t2 = df['B'] + s2
t3 = df['C'] + s3

new_df = pd.concat([t1,t2,t3],axis = 1)
new_df['total'] = new_df.sum(axis=1)
new_df

0   1    2  total
0   6  20  115    141
1   7  30  215    252
2   8  40  315    363
3   9  50  415    474
4  10  60  515    585

In [11]:
# 여러 열에 시리즈를 더하고 새로운 데이터프레임 생성
df_new = df.copy()
df_new['A'] = df['A'] + s1
df_new['B'] = df['B'] + s2
df_new['C'] = df['C'] + s3

# 각 행의 합계를 계산하여 새로운 열 추가
df_new['Sum'] = df_new.sum(axis = 1)

print(df_new)

    A   B    C  Sum
0   6  20  115  141
1   7  30  215  252
2   8  40  315  363
3   9  50  415  474
4  10  60  515  585


#### 그룹 연산
* 복잡한 데이터를 어떤 기준에 따라 여러 그룹으로 나누어서 관찰할 수 있으며 이런 방식으로 분할 처리하는 것을 그룹 연산이라 함
* 그룹 연산은 데이터를 집계, 변환, 필터링하는데 효율적이며 판다스 groupby() 메소드를 사용함
* 그룹 객체 만들기(분할)
* 그룹 연산 메소드(적용-결합)

In [ ]:
import pandas as pd
import seaborn as sns

# titanic 데이터셋에서 age, sex 등 5개 열을 선택하여 데이터프레임 만들기
titanic = sns.load_dataset('titanic')
df = titanic.loc[:,['age','sex','class','fare','survived']]
# df = titanic[['age','sex','class','fare','survived']]
print('승객 수:',len(df))
print(df.head())

승객 수: 891
    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
1  38.0  female  First  71.2833         1
2  26.0  female  Third   7.9250         1
3  35.0  female  First  53.1000         1
4  35.0    male  Third   8.0500         0


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype   
---  ------    --------------  -----   
 0   age       714 non-null    float64 
 1   sex       891 non-null    object  
 2   class     891 non-null    category
 3   fare      891 non-null    float64 
 4   survived  891 non-null    int64   
dtypes: category(1), float64(2), int64(1), object(1)
memory usage: 29.0+ KB


In [ ]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [14]:
# Task4_0528. df에서 세 열의 값을 더하여 새로운 컬럼을 생성한 후 출력하세요.

import pandas as pd

# 데이터프레임 생성
df = pd.DataFrame({
    "A": [10, 20, 30, 40, 50],
    "B": [1, 2, 3, 4, 5],
    "C": [5, 10, 15, 20, 25],
    "D": [3, 6, 9, 12, 15],
    "E": [2, 4, 6, 8, 10]
})


In [13]:
df['A+B+C'] = df.loc[:,'A':'C'].sum(axis=1)
df

A  B   C   D   E  A+B+C
0  10  1   5   3   2     16
1  20  2  10   6   4     32
2  30  3  15   9   6     48
3  40  4  20  12   8     64
4  50  5  25  15  10     80

In [15]:
df['A_B_C_sum'] = df['A']+df['B']+df['C']

print(df)

    A  B   C   D   E  A_B_C_sum
0  10  1   5   3   2         16
1  20  2  10   6   4         32
2  30  3  15   9   6         48
3  40  4  20  12   8         64
4  50  5  25  15  10         80


In [19]:
# Task5_0528. df에서 세 열의 값을 평균하여 새로운 컬럼을 생성 후 출력하세요.

import pandas as pd

# 데이터프레임 생성
df = pd.DataFrame({
    "A": [100, 200, 300, 400, 500],
    "B": [10, 20, 30, 40, 50],
    "C": [1, 2, 3, 4, 5],
    "D": [7, 8, 9, 10, 11],
    "E": [3, 6, 9, 12, 15]
})


In [17]:
df['A,B,C의 mean'] = df.loc[:,'A':'C'].mean(axis=1)
df

A   B  C   D   E  A,B,C의 mean
0  100  10  1   7   3         37.0
1  200  20  2   8   6         74.0
2  300  30  3   9   9        111.0
3  400  40  4  10  12        148.0
4  500  50  5  11  15        185.0

In [20]:
df['ABC_mean'] = df[['A','B','C']].mean(axis = 1)

print(df)

     A   B  C   D   E  ABC_mean
0  100  10  1   7   3      37.0
1  200  20  2   8   6      74.0
2  300  30  3   9   9     111.0
3  400  40  4  10  12     148.0
4  500  50  5  11  15     185.0


In [21]:
# Task6_0528. df에서 두 개의 열을 더한 값이 다른 한 개의 열보다 큰 경우에는 1, 작은 경우에는 0으로 값을 정하는 새로운 열을 생성한 후 출력하세요.

import pandas as pd

# 데이터프레임 생성
df = pd.DataFrame({
    "A": [2, 3, 4, 5, 6],
    "B": [1, 2, 3, 4, 5],
    "C": [3, 4, 5, 6, 7],
    "D": [8, 9, 10, 11, 12],
    "E": [10, 20, 30, 40, 50]
})


In [ ]:
t = df['A']+df['B'] > df['C']
t_to_int = t.astype(int)
df['bool'] = t_to_int
df

A  B  C   D   E  bool
0  2  1  3   8  10     0
1  3  2  4   9  20     1
2  4  3  5  10  30     1
3  5  4  6  11  40     1
4  6  5  7  12  50     1

In [ ]:
df['A_B_greater_than_C'] = (df['A']+df['B'] > df['C']).astype(int)

df