## 1번

In [ ]:
# Task1_0611. 주어진 대각 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

D = np.diag([1, 2, 3])
d = np.linalg.inv(D)
print(f"역행렬인지 확인 \n {np.dot(D,d)}")

역행렬인지 확인 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 2번

In [ ]:
# Task2_0611. 임의의 상삼각 행렬을 생성하고, 그 행렬로 부터 하삼각 행렬을 구하여 출력하세요.

mx = np.triu(np.arange(9).reshape(3,3))
print(f"상삼각 행렬\n{mx}")
mx1 = np.tril(mx)
print(f"상삼각 -> 하삼각 행렬\n{mx1}")

상삼각 행렬
[[0 1 2]
 [0 4 5]
 [0 0 8]]
상삼각 -> 하삼각 행렬
[[0 0 0]
 [0 4 0]
 [0 0 8]]


In [ ]:
import numpy as np
U = np.array([[1,2,3],[0,4,5],[0,0,6]])

U_T = U.T

print(f"Upper Triangular Matrix U=\n {U}")
print(f"Transpose of U =\n {U_T}")

Upper Triangular Matrix U=
 [[1 2 3]
 [0 4 5]
 [0 0 6]]
Transpose of U =
 [[1 0 0]
 [2 4 0]
 [3 5 6]]


## 3번

In [ ]:
# Task3_0611. 주어진 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

A = np.array([[4, 7], [2, 6]])
a = np.linalg.inv(A)
print(f"역행렬인지 확인 \n {np.matmul(A,a)}")

역행렬인지 확인 
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


In [ ]:
A = np.array([[4, 7], [2, 6]])

A_inv = np.linalg.inv(A)

result = np.dot(A,A_inv)

l = np.eye(2)

print(f"A=\n {A}")
print(f"A_inv=\n {A_inv}")
print(f"A * A_inv =\n {result}")
print(f"Is A * A_inv equal to l? {np.allclose(result,l)}")

A=
 [[4 7]
 [2 6]]
A_inv=
 [[ 0.6 -0.7]
 [-0.2  0.4]]
A * A_inv =
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
Is A * A_inv equal to l? True


## 4번

In [ ]:
# Task4_0611. 주어진 데이터 포인트와 모델 파라미터를 사용하여 선형 회귀 모델의 예측값을 계산하세요.
# - 1단계 : 주어진 입력 데이터 포인트 X와 모델 파라미터 θ를 정의.
# - 2단계 : 행렬 곱을 사용하여 예측값 y를 계산.
X = np.array([1, 2, 3])
x = np.array([6,7,8])
y = np.dot(X,x)
print(f"예측값:\n{y}")


예측값:
44


In [ ]:

# 입력 데이터 포인트 (1,x1,x2)
X = np.array([1, 2, 3])

# 모델 파라미터(bias, w1, w2)
theta = np.array([0.5,1.5,-2])

# 선형 회귀 모델의 예측값 계산
y_pred = np.dot(X,theta)

print(f"Input Data Point X = {X}")
print(f"Model Parameters theta = {theta}")
print(f"Predicted Value y = {y_pred}")

## 5번

Task5_0611. 주어진 입력 벡터와 가중치 행렬을 사용하여 신경망의 단일 계층 출력을 계산하세요.

- 1단계: 입력 벡터 X와 가중치 행렬 W를 정의.
- 2단계: 행렬 곱을 사용하여 계층의 출력을 계산.

In [ ]:
# Task5_0611

X = np.array([0.5, 1.0, -1.5])
W = np.array([[4],[5],[3]])
print(f"단일 계층 출력: {np.dot(X,W)}")

단일 계층 출력: [2.5]


In [ ]:
X = np.array([0.5, 1.0, -1.5])

W = np.array([[0.2,-0.3,0.5],
              [0.4,0.1,-0.2],
              [-0.5,0.4,0.3]])

# 가중치 행렬과 입력벡터의 일반적인 표기방법은 WX
output = np.dot(W,X)

print(f"Input Vector X = {X}")
print(f"Weight Matrix W = \n {W}")
# numpy에서 알아서 전치하여 출력
print(f"Layer Output = {output}")
print(output.ndim)
print(output.T)

Input Vector X = [ 0.5  1.  -1.5]
Weight Matrix W = 
 [[ 0.2 -0.3  0.5]
 [ 0.4  0.1 -0.2]
 [-0.5  0.4  0.3]]
Layer Output = [-0.95  0.6  -0.3 ]
1
[-0.95  0.6  -0.3 ]


## 6번

Task6_0611. 주어진 입력 벡터에 대해 신경망의 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산하세요.

X = np.array([1, -2, 3])

- 1단계: 입력 벡터 X를 정의.
- 2단계: 가중치 행렬 W와 편향 벡터 b를 정의.
- 3단계: 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산
활성화 함수 적용<br>
output_relu = relu(Z)<br>
output_sigmoid = sigmoid(Z)

In [ ]:
# Task6_0611
def relu(x):
    return np.maximum(0, x)

X = np.array([1, -2, 3])
W = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([1,2,3])
result = np.dot(X,W)
Z= result+b
output_relu = relu(Z)
print("결과:", output_relu)

결과: [15 18 21]


In [ ]:
# 활성화 함수 정의
def relu(x):
    # 음수이면 0 그외는 x(비선형변환)
    return np.maximum(0,x)

def sigmoid(x):
    # 0.5보다 크면 1, 작으면 0으로 바꿔주는 식(비선형변환)
    return 1 / (1+np.exp(-x))

# 입력 벡터
X = np.array([1, -2, 3])

# 가중치 행렬과 편향 벡터 정의
W = np.array([[0.2,-0.5,0.3],
              [0.4,0.1,-0.2],
              [-0.3,-.4,-.6]])
b = np.array([0.1,-0.2,0.3])

# 신경망의 선형 변환 계산
Z = np.dot(W,X) + b

# 활성화 함수 적용
output_relu = relu(Z)
output_sigmoid = sigmoid(Z)

print("Input Vector X =",X)
print('Weight Matrix W =\n',W)
print("Bias Vector b =",b)
print("Linear Transformation Z =\n",Z)
print(output_relu)
print(output_sigmoid)

Input Vector X = [ 1 -2  3]
Weight Matrix W =
 [[ 0.2 -0.5  0.3]
 [ 0.4  0.1 -0.2]
 [-0.3 -0.4 -0.6]]
Bias Vector b = [ 0.1 -0.2  0.3]
Linear Transformation Z =
 [ 2.2 -0.6 -1. ]
[2.2 0.  0. ]
[0.90024951 0.35434369 0.26894142]


## 7번

Task7_0611. 주어진 선형 방정식을 행렬 형태로 나타내고, 역행렬을 사용하여
x와 y를 구하세요.

$\begin{cases}
3x + 4y = 10 \\
2x + y = 5
\end{cases}$

단계:
1. 계수 행렬 A와 결과 벡터 b를 정의.
2. 행렬 A의 역행렬을 구한다.
3. 역행렬을 사용하여 변수 x를 구한다.

[풀이]
주어진 선형방정식을 행렬 형태로 나타내면 다음과 같다: \\
$A\mathbf{x} = \mathbf{b}$ \\
여기서 \\
$A = \begin{bmatrix}3 & 4 \\2 & 1\end{bmatrix}$,

$\mathbf{x} = \begin{bmatrix}x \\y\end{bmatrix}$,

$\mathbf{b} = \begin{bmatrix}10 \\5\end{bmatrix}$

$\mathbf{x} = A^{-1} \mathbf{b}$

In [ ]:
# 계수 행렬 A와 결과 벡터 b 정의
A = np.array([[3,4],[2,1]])
b = np.array([10,5])
a = np.linalg.inv(A)
result = np.dot(a,b)
print("변수의 값",result)


변수의 값 [2. 1.]


## 8번

Task8_0611. 주어진 2D 평면의 점을 특정 변환 행렬을 사용하여 변환한 후, 변환된 좌표를 원래 좌표로 되돌리세요.

원래 점의 좌표 p와 변환 행렬 T 정의<br>
p = np.array([1, 2])<br>
T = np.array([[2, 0], [0, 3]])

단계
1. 원래 점의 좌표 p와 변환 행렬 T를 정의.
2. 변환 행렬 T를 사용하여 새로운 좌표 p를 계산.
3. 변환 행렬 T의 역행렬을 사용하여 새로운 좌표 p에서 원래 좌표 p를 복원.

In [ ]:
p = np.array([1, 2])
T = np.array([[2, 0], [0, 3]])

p1 = np.dot(p,T) #새로운 좌표
t = np.linalg.inv(T)
p2 = np.dot(p1,t)
print(np.allclose(p,p2)) #원래 좌표와 맞는지 확인

True


In [ ]:
p = np.array([1, 2])
T = np.array([[2, 0], [0, 3]])

# 새로운 좌표
p_prime = np.dot(T,p)

# 변환 행렬 T의 역행렬 계산
T_inv = np.linalg.inv(T)

# 원래 좌표 p 복원
p_restored=np.dot(T_inv,p_prime)

print(p)
print(p_restored)

[1 2]
[1. 2.]
